making a dataset

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
data = {"calories": [420, 380, 390],
        "duration": [50, 40, 45]}

In [ ]:
df=pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

importing dataset

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving student.csv to student.csv

In [ ]:
df = pd.read_csv("student.csv")

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.head(10)

   id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78     NaN
9  10     Big John   Four    55  female

In [ ]:
df.tail()

    id         name  class  mark  gender
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.sample()

    id       name class  mark  gender
32  33  Kenn Rein   Six    96  female

In [ ]:
df.sample(3)

    id         name  class  mark gender
6    7  My John Rob  Fifth    78   male
22  23        Herod  Eight    79   male
28  29  Tess Played  Seven    55   male

In [ ]:
df.shape

(35, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [ ]:
df.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [ ]:
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.isnull().sum()

id        0
name      1
class     1
mark      0
gender    2
dtype: int64

In [ ]:
df.dtypes

id         int64
name      object
class     object
mark       int64
gender    object
dtype: object

subsetting a dataframe

In [ ]:
df["name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [ ]:
df["class"].head()

0     Four
1    Three
2    Three
3     Four
4     Four
Name: class, dtype: object

In [ ]:
df["mark"].mean()

74.65714285714286

In [ ]:
df["mark"].max()

96

In [ ]:
df[["name","gender","id"]].sample()

     name gender  id
18  Tinny   male  19

using indexes

In [ ]:
df["name"][0:2]

0    John Deo
1    Max Ruin
Name: name, dtype: object

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df[1:5]

   id        name  class  mark  gender
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df["name"][0:2]

0    John Deo
1    Max Ruin
Name: name, dtype: object

Loc and iLoc

In [ ]:
df.loc[0, "name"] # first row and name column
# loc[rows, columns]

'John Deo'

In [ ]:
df.loc[3, "mark"]

60

In [ ]:
df.loc[3, ["name", "mark"]]

name    Krish Star
mark            60
Name: 3, dtype: object

In [ ]:
df.loc[0:3, ["name", "mark"]]

         name  mark
0    John Deo    75
1    Max Ruin    85
2      Arnold    55
3  Krish Star    60

In [ ]:
df.iloc[3,3]

60

In [ ]:
df.iloc[0:3, [1,2]]

       name  class
0  John Deo   Four
1  Max Ruin  Three
2    Arnold  Three

Filtering

In [ ]:
df[df["mark"]>90]

    id       name class  mark  gender
11  12      Recky   Six    94  female
32  33  Kenn Rein   Six    96  female

In [ ]:
df.loc[df["mark"]>90, :]

    id       name class  mark  gender
11  12      Recky   Six    94  female
32  33  Kenn Rein   Six    96  female

In [ ]:
df[df["gender"]=="female"]

    id        name  class  mark  gender
0    1    John Deo   Four    75  female
3    4  Krish Star   Four    60  female
4    5   John Mike   Four    60  female
9   10    Big John   Four    55  female
10  11      Ronald    Six    89  female
11  12       Recky    Six    94  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
19  20      Jackly   Nine    65  female
20  21  Babby John   Four    69  female
21  22      Reggid  Seven    55  female
27  28   Rojj Base  Seven    86  female
29  30   Reppy Red    Six    79  female
31  32   Binn Rott  Seven    90  female
32  33   Kenn Rein    Six    96  female
34  35  Rows Noump    Six    88  female

In [ ]:
df.loc[df["gender"]=="female", :]

    id        name  class  mark  gender
0    1    John Deo   Four    75  female
3    4  Krish Star   Four    60  female
4    5   John Mike   Four    60  female
9   10    Big John   Four    55  female
10  11      Ronald    Six    89  female
11  12       Recky    Six    94  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
19  20      Jackly   Nine    65  female
20  21  Babby John   Four    69  female
21  22      Reggid  Seven    55  female
27  28   Rojj Base  Seven    86  female
29  30   Reppy Red    Six    79  female
31  32   Binn Rott  Seven    90  female
32  33   Kenn Rein    Six    96  female
34  35  Rows Noump    Six    88  female

In [ ]:
df.loc[df["gender"]=="female", ["name", "class", "gender"]]

          name  class  gender
0     John Deo   Four  female
3   Krish Star   Four  female
4    John Mike   Four  female
9     Big John   Four  female
10      Ronald    Six  female
11       Recky    Six  female
12         Kty  Seven  female
13        Bigy  Seven  female
19      Jackly   Nine  female
20  Babby John   Four  female
21      Reggid  Seven  female
27   Rojj Base  Seven  female
29   Reppy Red    Six  female
31   Binn Rott  Seven  female
32   Kenn Rein    Six  female
34  Rows Noump    Six  female

filtering by 2 criteria

In [ ]:
df[(df["gender"]=="female") & (df["class"]=="Six")]

    id        name class  mark  gender
10  11      Ronald   Six    89  female
11  12       Recky   Six    94  female
29  30   Reppy Red   Six    79  female
32  33   Kenn Rein   Six    96  female
34  35  Rows Noump   Six    88  female

In [ ]:
df.loc[(df["gender"]=="female") & (df["class"]=="Six"), :]

    id        name class  mark  gender
10  11      Ronald   Six    89  female
11  12       Recky   Six    94  female
29  30   Reppy Red   Six    79  female
32  33   Kenn Rein   Six    96  female
34  35  Rows Noump   Six    88  female

In [ ]:
df["mark"].mean()

74.65714285714286

Average mark across male and female students

In [ ]:
df[df["gender"] == "female"]["mark"].mean()

77.3125

average mark for male

In [ ]:
df[df["gender"] == "male"]["mark"].mean()

71.58823529411765

Max and min mark

In [ ]:
df["mark"].min()

18

In [ ]:
df["mark"].max()

96

Max mark for male and female students

In [ ]:
df[df["gender"] == "male"]["mark"].max()

88

In [ ]:
df[df["gender"] == "female"]["mark"].max()

96

Average mark for class 'Five'

In [ ]:
df[df["class"] == "Five"]["mark"].mean()

80.0

Average mark for class 'Six' and male students only

In [ ]:
df[(df["class"] == "Six") & (df["gender"] == "male")]["mark"].mean()

54.0

In [ ]:
df.loc[(df["class"]=="Six") & (df["gender"]=="male")]["mark"].mean()

54.0

In [ ]:
df[(df["gender"]=="male") & (df["class"]=="Six")]["mark"].mean()

54.0

group by - to group results as previously searched separately

In [ ]:
df.groupby("gender")["mark"].mean()

gender
female    77.312500
male      71.588235
Name: mark, dtype: float64

student who has lowest mark (18)

In [ ]:
df[df["mark"]==18]

    id   name class  mark gender
18  19  Tinny  Nine    18   male

In [ ]:
df.loc[df["mark"]==df['mark'].min()]

    id   name class  mark gender
18  19  Tinny  Nine    18   male

Sorting results

In [ ]:
df.sort_values(by="name")

    id         name  class  mark  gender
5    6    Alex John   Four    55    male
2    3       Arnold  Three    55    male
7    8       Asruid   Five    85    male
20  21   Babby John   Four    69  female
9   10     Big John   Four    55  female
13  14         Bigy  Seven    88  female
31  32    Binn Rott  Seven    90  female
25  26       Crelea  Seven    79    male
33  34     Gain Toe  Seven    69    male
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
22  23        Herod  Eight    79    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
0    1     John Deo   Four    75  female
4    5    John Mike   Four    60  female
32  33    Kenn Rein    Six    96  female
3    4   Krish Star   Four    60  female
12  13          Kty  Seven    88  female
30  31  Marry Toeey   Four    88    male
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
11  12        Recky    Six    94  female
21  22       Reggid  Seven    55  female
29  30    Reppy Red    Six    79  female
27  28    Rojj Base  Seven    86  female
10  11       Ronald    Six    89  female
34  35   Rows Noump    Six    88  female
14  15     Tade Row    NaN    88    male
8    9      Tes Qry    Six    78     NaN
28  29  Tess Played  Seven    55    male
23  24    Tiddy Now  Seven    78    male
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
26  27          NaN  Three    81     NaN

sorting ascending or descending order

In [ ]:
df.sort_values(by="name", ascending=False)

    id         name  class  mark  gender
16  17        Tumyu    Six    54    male
18  19        Tinny   Nine    18    male
23  24    Tiddy Now  Seven    78    male
28  29  Tess Played  Seven    55    male
8    9      Tes Qry    Six    78     NaN
14  15     Tade Row    NaN    88    male
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
27  28    Rojj Base  Seven    86  female
29  30    Reppy Red    Six    79  female
21  22       Reggid  Seven    55  female
11  12        Recky    Six    94  female
6    7  My John Rob  Fifth    78    male
1    2     Max Ruin  Three    85    male
30  31  Marry Toeey   Four    88    male
12  13          Kty  Seven    88  female
3    4   Krish Star   Four    60  female
32  33    Kenn Rein    Six    96  female
4    5    John Mike   Four    60  female
0    1     John Deo   Four    75  female
19  20       Jackly   Nine    65  female
17  18        Honny   Five    75    male
22  23        Herod  Eight    79    male
15  16        Gimmy   Four    88    male
24  25     Giff Tow  Seven    88    male
33  34     Gain Toe  Seven    69    male
25  26       Crelea  Seven    79    male
31  32    Binn Rott  Seven    90  female
13  14         Bigy  Seven    88  female
9   10     Big John   Four    55  female
20  21   Babby John   Four    69  female
7    8       Asruid   Five    85    male
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
26  27          NaN  Three    81     NaN

In [ ]:
df.sort_values(by="name", ascending=True)

    id         name  class  mark  gender
5    6    Alex John   Four    55    male
2    3       Arnold  Three    55    male
7    8       Asruid   Five    85    male
20  21   Babby John   Four    69  female
9   10     Big John   Four    55  female
13  14         Bigy  Seven    88  female
31  32    Binn Rott  Seven    90  female
25  26       Crelea  Seven    79    male
33  34     Gain Toe  Seven    69    male
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
22  23        Herod  Eight    79    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
0    1     John Deo   Four    75  female
4    5    John Mike   Four    60  female
32  33    Kenn Rein    Six    96  female
3    4   Krish Star   Four    60  female
12  13          Kty  Seven    88  female
30  31  Marry Toeey   Four    88    male
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
11  12        Recky    Six    94  female
21  22       Reggid  Seven    55  female
29  30    Reppy Red    Six    79  female
27  28    Rojj Base  Seven    86  female
10  11       Ronald    Six    89  female
34  35   Rows Noump    Six    88  female
14  15     Tade Row    NaN    88    male
8    9      Tes Qry    Six    78     NaN
28  29  Tess Played  Seven    55    male
23  24    Tiddy Now  Seven    78    male
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
26  27          NaN  Three    81     NaN

limit the results to a specific number while sorting ascending/descending

In [ ]:
df.sort_values(by="mark", ascending=False).head(10)

    id        name  class  mark  gender
32  33   Kenn Rein    Six    96  female
11  12       Recky    Six    94  female
31  32   Binn Rott  Seven    90  female
10  11      Ronald    Six    89  female
24  25    Giff Tow  Seven    88    male
15  16       Gimmy   Four    88    male
14  15    Tade Row    NaN    88    male
13  14        Bigy  Seven    88  female
12  13         Kty  Seven    88  female
34  35  Rows Noump    Six    88  female

using OR

In [ ]:
df[(df["gender"]=="female") | (df["class"]=="Seven")].sort_values(by="mark")

    id         name  class  mark  gender
21  22       Reggid  Seven    55  female
9   10     Big John   Four    55  female
28  29  Tess Played  Seven    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
33  34     Gain Toe  Seven    69    male
20  21   Babby John   Four    69  female
0    1     John Deo   Four    75  female
23  24    Tiddy Now  Seven    78    male
25  26       Crelea  Seven    79    male
29  30    Reppy Red    Six    79  female
27  28    Rojj Base  Seven    86  female
12  13          Kty  Seven    88  female
24  25     Giff Tow  Seven    88    male
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

value counts - used to count the unique values in each column

In [ ]:
df["class"].value_counts()

class
Seven    10
Four      8
Six       7
Three     3
Five      2
Nine      2
Fifth     1
Eight     1
Name: count, dtype: int64

In [ ]:
df["gender"].value_counts()

gender
male      17
female    16
Name: count, dtype: int64